<?php
/**
 * QueryEntitiesResponseEntityListInner
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Nutanix Intentful API
 *
 * Move programming from the user to the machine.
 *
 * The version of the OpenAPI document: 3.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * QueryEntitiesResponseEntityListInner Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class QueryEntitiesResponseEntityListInner implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'query_entities_response_entity_list_inner';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'error_reason_list' => '\OpenAPI\Client\Model\QueryEntitiesResponseEntityListInnerErrorReasonListInner[]',
        'entity_reference' => '\OpenAPI\Client\Model\Reference',
        'protection_status' => 'string',
        'protection_rule_reference' => '\OpenAPI\Client\Model\ProtectionRuleReference'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'error_reason_list' => null,
        'entity_reference' => null,
        'protection_status' => null,
        'protection_rule_reference' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'error_reason_list' => false,
        'entity_reference' => false,
        'protection_status' => false,
        'protection_rule_reference' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'error_reason_list' => 'error_reason_list',
        'entity_reference' => 'entity_reference',
        'protection_status' => 'protection_status',
        'protection_rule_reference' => 'protection_rule_reference'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'error_reason_list' => 'setErrorReasonList',
        'entity_reference' => 'setEntityReference',
        'protection_status' => 'setProtectionStatus',
        'protection_rule_reference' => 'setProtectionRuleReference'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'error_reason_list' => 'getErrorReasonList',
        'entity_reference' => 'getEntityReference',
        'protection_status' => 'getProtectionStatus',
        'protection_rule_reference' => 'getProtectionRuleReference'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('error_reason_list', $data ?? [], null);
        $this->setIfExists('entity_reference', $data ?? [], null);
        $this->setIfExists('protection_status', $data ?? [], null);
        $this->setIfExists('protection_rule_reference', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets error_reason_list
     *
     * @return \OpenAPI\Client\Model\QueryEntitiesResponseEntityListInnerErrorReasonListInner[]|null
     */
    public function getErrorReasonList()
    {
        return $this->container['error_reason_list'];
    }

    /**
     * Sets error_reason_list
     *
     * @param \OpenAPI\Client\Model\QueryEntitiesResponseEntityListInnerErrorReasonListInner[]|null $error_reason_list List of errors because of which protection of entity is not possible.
     *
     * @return self
     */
    public function setErrorReasonList($error_reason_list)
    {
        if (is_null($error_reason_list)) {
            throw new \InvalidArgumentException('non-nullable error_reason_list cannot be null');
        }
        $this->container['error_reason_list'] = $error_reason_list;

        return $this;
    }

    /**
     * Gets entity_reference
     *
     * @return \OpenAPI\Client\Model\Reference|null
     */
    public function getEntityReference()
    {
        return $this->container['entity_reference'];
    }

    /**
     * Sets entity_reference
     *
     * @param \OpenAPI\Client\Model\Reference|null $entity_reference entity_reference
     *
     * @return self
     */
    public function setEntityReference($entity_reference)
    {
        if (is_null($entity_reference)) {
            throw new \InvalidArgumentException('non-nullable entity_reference cannot be null');
        }
        $this->container['entity_reference'] = $entity_reference;

        return $this;
    }

    /**
     * Gets protection_status
     *
     * @return string|null
     */
    public function getProtectionStatus()
    {
        return $this->container['protection_status'];
    }

    /**
     * Sets protection_status
     *
     * @param string|null $protection_status Protection status of the entity. CAN_BE_PROTECTED would mean that there are no errors for this entity and it can be protected. PROTECTED status would mean that the entity is protected by the same protection policy passed in the arg. PARTIALLY_PROTECTED would mean that the entity is protected by the same protection policy passed in the arg but also has some errors associated with it. CANNOT_BE_PROTECTED would mean that the entities aren't protected by the protection policy passed in the arg and have errors associated with it.
     *
     * @return self
     */
    public function setProtectionStatus($protection_status)
    {
        if (is_null($protection_status)) {
            throw new \InvalidArgumentException('non-nullable protection_status cannot be null');
        }
        $this->container['protection_status'] = $protection_status;

        return $this;
    }

    /**
     * Gets protection_rule_reference
     *
     * @return \OpenAPI\Client\Model\ProtectionRuleReference|null
     */
    public function getProtectionRuleReference()
    {
        return $this->container['protection_rule_reference'];
    }

    /**
     * Sets protection_rule_reference
     *
     * @param \OpenAPI\Client\Model\ProtectionRuleReference|null $protection_rule_reference protection_rule_reference
     *
     * @return self
     */
    public function setProtectionRuleReference($protection_rule_reference)
    {
        if (is_null($protection_rule_reference)) {
            throw new \InvalidArgumentException('non-nullable protection_rule_reference cannot be null');
        }
        $this->container['protection_rule_reference'] = $protection_rule_reference;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


