<?php
/**
 * SshUserRequestDetails
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Nutanix Intentful API
 *
 * Move programming from the user to the machine.
 *
 * The version of the OpenAPI document: 3.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * SshUserRequestDetails Class Doc Comment
 *
 * @category Class
 * @description SSH User Request details
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SshUserRequestDetails implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ssh_user_request_details';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'username' => 'string',
        'entity_list' => '\OpenAPI\Client\Model\SshUserRequestDetailsEntityListInner[]',
        'user_key_name' => 'string',
        'user_key' => 'string',
        'user_unix_id' => 'int',
        'access_request_uuid' => 'string',
        'user_uuid' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'username' => null,
        'entity_list' => null,
        'user_key_name' => null,
        'user_key' => null,
        'user_unix_id' => null,
        'access_request_uuid' => 'UUID',
        'user_uuid' => 'UUID'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'username' => false,
        'entity_list' => false,
        'user_key_name' => false,
        'user_key' => false,
        'user_unix_id' => false,
        'access_request_uuid' => false,
        'user_uuid' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'username' => 'username',
        'entity_list' => 'entity_list',
        'user_key_name' => 'user_key_name',
        'user_key' => 'user_key',
        'user_unix_id' => 'user_unix_id',
        'access_request_uuid' => 'access_request_uuid',
        'user_uuid' => 'user_uuid'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'username' => 'setUsername',
        'entity_list' => 'setEntityList',
        'user_key_name' => 'setUserKeyName',
        'user_key' => 'setUserKey',
        'user_unix_id' => 'setUserUnixId',
        'access_request_uuid' => 'setAccessRequestUuid',
        'user_uuid' => 'setUserUuid'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'username' => 'getUsername',
        'entity_list' => 'getEntityList',
        'user_key_name' => 'getUserKeyName',
        'user_key' => 'getUserKey',
        'user_unix_id' => 'getUserUnixId',
        'access_request_uuid' => 'getAccessRequestUuid',
        'user_uuid' => 'getUserUuid'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('username', $data ?? [], null);
        $this->setIfExists('entity_list', $data ?? [], null);
        $this->setIfExists('user_key_name', $data ?? [], null);
        $this->setIfExists('user_key', $data ?? [], null);
        $this->setIfExists('user_unix_id', $data ?? [], null);
        $this->setIfExists('access_request_uuid', $data ?? [], null);
        $this->setIfExists('user_uuid', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['username'] === null) {
            $invalidProperties[] = "'username' can't be null";
        }
        if ($this->container['entity_list'] === null) {
            $invalidProperties[] = "'entity_list' can't be null";
        }
        if ($this->container['user_key_name'] === null) {
            $invalidProperties[] = "'user_key_name' can't be null";
        }
        if ($this->container['user_key'] === null) {
            $invalidProperties[] = "'user_key' can't be null";
        }
        if ($this->container['access_request_uuid'] === null) {
            $invalidProperties[] = "'access_request_uuid' can't be null";
        }
        if (!preg_match("/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/", $this->container['access_request_uuid'])) {
            $invalidProperties[] = "invalid value for 'access_request_uuid', must be conform to the pattern /^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/.";
        }

        if ($this->container['user_uuid'] === null) {
            $invalidProperties[] = "'user_uuid' can't be null";
        }
        if (!preg_match("/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/", $this->container['user_uuid'])) {
            $invalidProperties[] = "invalid value for 'user_uuid', must be conform to the pattern /^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets username
     *
     * @return string
     */
    public function getUsername()
    {
        return $this->container['username'];
    }

    /**
     * Sets username
     *
     * @param string $username SSH User name
     *
     * @return self
     */
    public function setUsername($username)
    {
        if (is_null($username)) {
            throw new \InvalidArgumentException('non-nullable username cannot be null');
        }
        $this->container['username'] = $username;

        return $this;
    }

    /**
     * Gets entity_list
     *
     * @return \OpenAPI\Client\Model\SshUserRequestDetailsEntityListInner[]
     */
    public function getEntityList()
    {
        return $this->container['entity_list'];
    }

    /**
     * Sets entity_list
     *
     * @param \OpenAPI\Client\Model\SshUserRequestDetailsEntityListInner[] $entity_list List containing entity IP and entity type for each entity
     *
     * @return self
     */
    public function setEntityList($entity_list)
    {
        if (is_null($entity_list)) {
            throw new \InvalidArgumentException('non-nullable entity_list cannot be null');
        }
        $this->container['entity_list'] = $entity_list;

        return $this;
    }

    /**
     * Gets user_key_name
     *
     * @return string
     */
    public function getUserKeyName()
    {
        return $this->container['user_key_name'];
    }

    /**
     * Sets user_key_name
     *
     * @param string $user_key_name Name for the user key to add
     *
     * @return self
     */
    public function setUserKeyName($user_key_name)
    {
        if (is_null($user_key_name)) {
            throw new \InvalidArgumentException('non-nullable user_key_name cannot be null');
        }
        $this->container['user_key_name'] = $user_key_name;

        return $this;
    }

    /**
     * Gets user_key
     *
     * @return string
     */
    public function getUserKey()
    {
        return $this->container['user_key'];
    }

    /**
     * Sets user_key
     *
     * @param string $user_key key to add for the user
     *
     * @return self
     */
    public function setUserKey($user_key)
    {
        if (is_null($user_key)) {
            throw new \InvalidArgumentException('non-nullable user_key cannot be null');
        }
        $this->container['user_key'] = $user_key;

        return $this;
    }

    /**
     * Gets user_unix_id
     *
     * @return int|null
     */
    public function getUserUnixId()
    {
        return $this->container['user_unix_id'];
    }

    /**
     * Sets user_unix_id
     *
     * @param int|null $user_unix_id Linux UID for user
     *
     * @return self
     */
    public function setUserUnixId($user_unix_id)
    {
        if (is_null($user_unix_id)) {
            throw new \InvalidArgumentException('non-nullable user_unix_id cannot be null');
        }
        $this->container['user_unix_id'] = $user_unix_id;

        return $this;
    }

    /**
     * Gets access_request_uuid
     *
     * @return string
     */
    public function getAccessRequestUuid()
    {
        return $this->container['access_request_uuid'];
    }

    /**
     * Sets access_request_uuid
     *
     * @param string $access_request_uuid UUID of the access request requesting SSH access
     *
     * @return self
     */
    public function setAccessRequestUuid($access_request_uuid)
    {
        if (is_null($access_request_uuid)) {
            throw new \InvalidArgumentException('non-nullable access_request_uuid cannot be null');
        }

        if ((!preg_match("/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/", ObjectSerializer::toString($access_request_uuid)))) {
            throw new \InvalidArgumentException("invalid value for \$access_request_uuid when calling SshUserRequestDetails., must conform to the pattern /^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/.");
        }

        $this->container['access_request_uuid'] = $access_request_uuid;

        return $this;
    }

    /**
     * Gets user_uuid
     *
     * @return string
     */
    public function getUserUuid()
    {
        return $this->container['user_uuid'];
    }

    /**
     * Sets user_uuid
     *
     * @param string $user_uuid SSH User UUID
     *
     * @return self
     */
    public function setUserUuid($user_uuid)
    {
        if (is_null($user_uuid)) {
            throw new \InvalidArgumentException('non-nullable user_uuid cannot be null');
        }

        if ((!preg_match("/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/", ObjectSerializer::toString($user_uuid)))) {
            throw new \InvalidArgumentException("invalid value for \$user_uuid when calling SshUserRequestDetails., must conform to the pattern /^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/.");
        }

        $this->container['user_uuid'] = $user_uuid;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


