<?php
/**
 * TriggerInstanceObject
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Nutanix Intentful API
 *
 * Move programming from the user to the machine.
 *
 * The version of the OpenAPI document: 3.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * TriggerInstanceObject Class Doc Comment
 *
 * @category Class
 * @description Trigger instance object.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TriggerInstanceObject implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'trigger_instance_object';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'instance_uuid' => 'string',
        'display_name' => 'string',
        'description' => 'string',
        'action_trigger_type_reference' => '\OpenAPI\Client\Model\ActionTriggerTypeReference',
        'output_parameters' => 'object',
        'input_parameter_values' => 'array<string,string>'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'instance_uuid' => 'UUID',
        'display_name' => null,
        'description' => null,
        'action_trigger_type_reference' => null,
        'output_parameters' => null,
        'input_parameter_values' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'instance_uuid' => false,
        'display_name' => false,
        'description' => false,
        'action_trigger_type_reference' => false,
        'output_parameters' => false,
        'input_parameter_values' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'instance_uuid' => 'instance_uuid',
        'display_name' => 'display_name',
        'description' => 'description',
        'action_trigger_type_reference' => 'action_trigger_type_reference',
        'output_parameters' => 'output_parameters',
        'input_parameter_values' => 'input_parameter_values'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'instance_uuid' => 'setInstanceUuid',
        'display_name' => 'setDisplayName',
        'description' => 'setDescription',
        'action_trigger_type_reference' => 'setActionTriggerTypeReference',
        'output_parameters' => 'setOutputParameters',
        'input_parameter_values' => 'setInputParameterValues'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'instance_uuid' => 'getInstanceUuid',
        'display_name' => 'getDisplayName',
        'description' => 'getDescription',
        'action_trigger_type_reference' => 'getActionTriggerTypeReference',
        'output_parameters' => 'getOutputParameters',
        'input_parameter_values' => 'getInputParameterValues'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('instance_uuid', $data ?? [], null);
        $this->setIfExists('display_name', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('action_trigger_type_reference', $data ?? [], null);
        $this->setIfExists('output_parameters', $data ?? [], null);
        $this->setIfExists('input_parameter_values', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['instance_uuid']) && !preg_match("/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/", $this->container['instance_uuid'])) {
            $invalidProperties[] = "invalid value for 'instance_uuid', must be conform to the pattern /^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/.";
        }

        if (!is_null($this->container['description']) && (mb_strlen($this->container['description']) > 255)) {
            $invalidProperties[] = "invalid value for 'description', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['description']) && !preg_match("/^[^&<>'\/\"]*$/", $this->container['description'])) {
            $invalidProperties[] = "invalid value for 'description', must be conform to the pattern /^[^&<>'\/\"]*$/.";
        }

        if ($this->container['action_trigger_type_reference'] === null) {
            $invalidProperties[] = "'action_trigger_type_reference' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets instance_uuid
     *
     * @return string|null
     */
    public function getInstanceUuid()
    {
        return $this->container['instance_uuid'];
    }

    /**
     * Sets instance_uuid
     *
     * @param string|null $instance_uuid Id to uniquely identify trigger in instance list.
     *
     * @return self
     */
    public function setInstanceUuid($instance_uuid)
    {
        if (is_null($instance_uuid)) {
            throw new \InvalidArgumentException('non-nullable instance_uuid cannot be null');
        }

        if ((!preg_match("/^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/", ObjectSerializer::toString($instance_uuid)))) {
            throw new \InvalidArgumentException("invalid value for \$instance_uuid when calling TriggerInstanceObject., must conform to the pattern /^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$/.");
        }

        $this->container['instance_uuid'] = $instance_uuid;

        return $this;
    }

    /**
     * Gets display_name
     *
     * @return string|null
     */
    public function getDisplayName()
    {
        return $this->container['display_name'];
    }

    /**
     * Sets display_name
     *
     * @param string|null $display_name Trigger display name.  This is for display name, hence ready-only.
     *
     * @return self
     */
    public function setDisplayName($display_name)
    {
        if (is_null($display_name)) {
            throw new \InvalidArgumentException('non-nullable display_name cannot be null');
        }
        $this->container['display_name'] = $display_name;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description The description of the trigger instance in the rule.
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        if ((mb_strlen($description) > 255)) {
            throw new \InvalidArgumentException('invalid length for $description when calling TriggerInstanceObject., must be smaller than or equal to 255.');
        }
        if ((!preg_match("/^[^&<>'\/\"]*$/", ObjectSerializer::toString($description)))) {
            throw new \InvalidArgumentException("invalid value for \$description when calling TriggerInstanceObject., must conform to the pattern /^[^&<>'\/\"]*$/.");
        }

        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets action_trigger_type_reference
     *
     * @return \OpenAPI\Client\Model\ActionTriggerTypeReference
     */
    public function getActionTriggerTypeReference()
    {
        return $this->container['action_trigger_type_reference'];
    }

    /**
     * Sets action_trigger_type_reference
     *
     * @param \OpenAPI\Client\Model\ActionTriggerTypeReference $action_trigger_type_reference action_trigger_type_reference
     *
     * @return self
     */
    public function setActionTriggerTypeReference($action_trigger_type_reference)
    {
        if (is_null($action_trigger_type_reference)) {
            throw new \InvalidArgumentException('non-nullable action_trigger_type_reference cannot be null');
        }
        $this->container['action_trigger_type_reference'] = $action_trigger_type_reference;

        return $this;
    }

    /**
     * Gets output_parameters
     *
     * @return object|null
     */
    public function getOutputParameters()
    {
        return $this->container['output_parameters'];
    }

    /**
     * Sets output_parameters
     *
     * @param object|null $output_parameters The trigger output parameter descriptors.  Came from trigger type.
     *
     * @return self
     */
    public function setOutputParameters($output_parameters)
    {
        if (is_null($output_parameters)) {
            throw new \InvalidArgumentException('non-nullable output_parameters cannot be null');
        }
        $this->container['output_parameters'] = $output_parameters;

        return $this;
    }

    /**
     * Gets input_parameter_values
     *
     * @return array<string,string>|null
     */
    public function getInputParameterValues()
    {
        return $this->container['input_parameter_values'];
    }

    /**
     * Sets input_parameter_values
     *
     * @param array<string,string>|null $input_parameter_values The trigger or action required input parameter value map, or the output parameters.
     *
     * @return self
     */
    public function setInputParameterValues($input_parameter_values)
    {
        if (is_null($input_parameter_values)) {
            throw new \InvalidArgumentException('non-nullable input_parameter_values cannot be null');
        }
        $this->container['input_parameter_values'] = $input_parameter_values;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


