<?php
/**
 * RecoveryPlanEntitiesEntitiesPerAvailabilityZoneListInnerEntityListInnerTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Nutanix Intentful API
 *
 * Move programming from the user to the machine.
 *
 * The version of the OpenAPI document: 3.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * RecoveryPlanEntitiesEntitiesPerAvailabilityZoneListInnerEntityListInnerTest Class Doc Comment
 *
 * @category    Class
 * @description RecoveryPlanEntitiesEntitiesPerAvailabilityZoneListInnerEntityListInner
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class RecoveryPlanEntitiesEntitiesPerAvailabilityZoneListInnerEntityListInnerTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "RecoveryPlanEntitiesEntitiesPerAvailabilityZoneListInnerEntityListInner"
     */
    public function testRecoveryPlanEntitiesEntitiesPerAvailabilityZoneListInnerEntityListInner()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "protection_status"
     */
    public function testPropertyProtectionStatus()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "recoverability"
     */
    public function testPropertyRecoverability()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "recovery_availability_zone_order_index"
     */
    public function testPropertyRecoveryAvailabilityZoneOrderIndex()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "is_recovery_point"
     */
    public function testPropertyIsRecoveryPoint()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "replication_status"
     */
    public function testPropertyReplicationStatus()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "any_entity_reference"
     */
    public function testPropertyAnyEntityReference()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
