<?php
/**
 * RecoveryPlanJobDefStatusValidationInformationTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Nutanix Intentful API
 *
 * Move programming from the user to the machine.
 *
 * The version of the OpenAPI document: 3.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * RecoveryPlanJobDefStatusValidationInformationTest Class Doc Comment
 *
 * @category    Class
 * @description The errors and warnings related to the Recovery Plan validation. Validation of the Recovery Plan will be done for all the actions performed on it. If there is any validation error for action other than validation, then the Recovery Plan execution will not be done.
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class RecoveryPlanJobDefStatusValidationInformationTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "RecoveryPlanJobDefStatusValidationInformation"
     */
    public function testRecoveryPlanJobDefStatusValidationInformation()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "errors_list"
     */
    public function testPropertyErrorsList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "warnings_list"
     */
    public function testPropertyWarningsList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
