<?php
/**
 * TheFieldsThatCanBeAllowedOrDisallowedDuringAnOperationTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Nutanix Intentful API
 *
 * Move programming from the user to the machine.
 *
 * The version of the OpenAPI document: 3.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * TheFieldsThatCanBeAllowedOrDisallowedDuringAnOperationTest Class Doc Comment
 *
 * @category    Class
 * @description The fields that can/cannot be accessed during the specified operation. field_name_list will be a list of fields. e.g. if field_mode &#x3D; disallowed, field_name_list &#x3D; [\&quot;xyz\&quot;] then the list of allowed fields is ALL fields minus xyz
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class TheFieldsThatCanBeAllowedOrDisallowedDuringAnOperationTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "TheFieldsThatCanBeAllowedOrDisallowedDuringAnOperation"
     */
    public function testTheFieldsThatCanBeAllowedOrDisallowedDuringAnOperation()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "field_mode"
     */
    public function testPropertyFieldMode()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "field_name_list"
     */
    public function testPropertyFieldNameList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
