<?php
/**
 * ReportsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Nutanix Intentful API
 *
 * Move programming from the user to the machine.
 *
 * The version of the OpenAPI document: 3.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ReportsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ReportsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for commonReportConfigsListPost
     *
     * List the common report configs..
     *
     */
    public function testCommonReportConfigsListPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for commonReportConfigsPost
     *
     * Create common report config..
     *
     */
    public function testCommonReportConfigsPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for commonReportConfigsUuidDelete
     *
     * Delete common report config..
     *
     */
    public function testCommonReportConfigsUuidDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for commonReportConfigsUuidGet
     *
     * Get common report config information..
     *
     */
    public function testCommonReportConfigsUuidGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for commonReportConfigsUuidPut
     *
     * Update common report config..
     *
     */
    public function testCommonReportConfigsUuidPut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reportConfigsListPost
     *
     * List the report configs..
     *
     */
    public function testReportConfigsListPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reportConfigsPost
     *
     * Create report config..
     *
     */
    public function testReportConfigsPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reportConfigsUuidDelete
     *
     * Delete report config..
     *
     */
    public function testReportConfigsUuidDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reportConfigsUuidGet
     *
     * Get report config information..
     *
     */
    public function testReportConfigsUuidGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reportConfigsUuidPut
     *
     * Update report config..
     *
     */
    public function testReportConfigsUuidPut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reportInstancesListPost
     *
     * Get the list of all the Generated report instances..
     *
     */
    public function testReportInstancesListPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reportInstancesPost
     *
     * Create a report instance..
     *
     */
    public function testReportInstancesPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reportInstancesUuidDelete
     *
     * Delete the generated report instance..
     *
     */
    public function testReportInstancesUuidDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reportInstancesUuidGet
     *
     * Get the specified report instance..
     *
     */
    public function testReportInstancesUuidGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reportsDownloadTypeUuidGet
     *
     * Download a resource..
     *
     */
    public function testReportsDownloadTypeUuidGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reportsNotifyPost
     *
     * Email the specified generated reports to specified recipients..
     *
     */
    public function testReportsNotifyPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reportsUploadTypePost
     *
     * Upload a file..
     *
     */
    public function testReportsUploadTypePost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
