name: tagged-release

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: Tagged Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install PHP dependencies
        uses: php-actions/composer@v5
        with:
          dev: no
          args: --profile --ignore-platform-reqs
      - name: Get the version
        id: get_version
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Create release file
        run: |
          rm -rf .git
          zip -r stinutanixsdk-${{ steps.get_version.outputs.SOURCE_TAG }}.zip .
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            stinutanixsdk-${{ steps.get_version.outputs.SOURCE_TAG }}.zip
